#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H

#define BOARD_UART_BAUD_RATE      (115200UL)
#define BOARD_UART_IRQ_PRIORITY   (5U)
#define BOARD_UART_RX_BUFFER_SIZE (128U)
#define BOARD_UART_TX_BUFFER_SIZE (128U)

#endif /* BOARD_CONFIG_H */
