#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H

#define BOARD_TIMEBASE_HZ       (1000UL)
#define BOARD_PWM_TIMER_TICK_HZ (1000000UL)
#define BOARD_PWM_FREQUENCY_HZ  (1000UL)

#endif /* BOARD_CONFIG_H */
